# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rajkumar R
tagline:          'Its A Wonderful Life'
#description:      'A curious mind trying to overcome its timidity.'
description:      'An inquisitive mind, dwelling in a eubstance, searching a course in the erratic life which is limited by its own timidity'
#url:              http://lanyon.getpoole.com

author:
  name:           'Rajkumar Ramasamy'
#url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.1

#github:
#repo:           https://github.com/rrajkumar/rrajkumar.github.io
